server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv23liZOhmmy8qsj9zpU
            client-secret: 1ec6f3d36bc9ed1ce1285c1843e0b5cbf219fd07