server:
  port: 8083

spring:
  application:
    name: storage-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud_demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    compatibility-verifier:
      enabled: false

dubbo:
  application:
    name: storage-service
    qos-enable: false
  protocol:
    port: 20882
  registry:
    address: nacos://127.0.0.1:8848

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

seata:
  enabled: true
  tx-service-group: cloud_tx_group
  service:
    vgroup-mapping:
      cloud_tx_group: default
    grouplist:
      default: 127.0.0.1:8091

management:
  endpoints:
    web:
      exposure:
        include: health,info
